---
title: "Resumo dos projetos"
author: "Filipe Penati"
date: "1 de julho de 2018"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Essa página apresenta um resumo dos projetos realizado na disciplina **"Análise de Dados e Introdução à Machine Learning"**.

***

## Projeto 1

* Título: Análise Exploratória de Dados
* Data: 2 de julho de 2018

### Descrição
Esse projeto tem como objetivo realizar uma análise exploratória nos dados sobre um experimento onde foi observado o peso de 50 pintinhos, nos 21 primeiros dias de vida, submetidos a 4 dietas diferentes.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 1](projetos/lesson1_analise-de-dados.html)

***

## Projeto 2

* Título: Problema de Regressão Linear
* Data: 2 de julho de 2018

### Descrição
Esse projeto tem como objetivo realizar a previsão de preço de apartamentos usando um modelo de regressão linear com multiatributos.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 2](projetos/lesson2_housingSmall.html)

## Projeto 3

* Título: Problema sob incerteza
* Data: 2 de julho de 2018

### Descrição
Esse projeto tem como objetivo encontrar um modelo que a apoie a gerência da BlueSky Airlines (fictícia) na definição dos limites de reservas de bilhetes antecipados para a semana de 19 de março de 2007 até de 25 de março de 2007. Para isso, são analisandos alguns modelos de previsão, baseados nos dados da demanda dos 12 meses anteriores, buscando aquele que apresente o menor erro.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 3](projetos/lesson3_BlueSky.html)

## Projeto 4

* Título: Problema de árvore de decisão
* Data: 2 de julho de 2018

### Descrição
O objetivo é prever se um bebê nascerá com baixo peso (menos que 2,5Kg). Os dados trazem informações sobre a mãe, o peso de bebês o nascer e o marcador “low”, quando o peso é menor que 2,5Kg.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 4](projetos/lesson4_birthwt.html)

## Projeto 5

* Título:  Problema de Regressão Logística
* Data: 2 de julho de 2018

### Descrição
O objetivo é prever se um bebê nascerá com baixo peso (menos que 2,5Kg) utilizando regressão logística. Os dados trazem informações sobre a mãe, o peso de bebês o nascer e o marcador “low”, quando o peso é menor que 2,5Kg.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 5](projetos/lesson5_birthwt_logisticregression.html)

## Projeto 6

* Título:  Problema de Regressão utilizando KNN
* Data: 2 de julho de 2018

### Descrição
O objetivo de exercício é construir um modelo para reconhecer a origem do vinho a partir das suas características, usando KNN Os dados apresentas 13 atributos com valores contínuos e mais um atributo (V1) com rótulos de classe de origem dos vinhos.

### Relatório do Projeto

Link no [meu Github](<https://github.com/penati>) *Pages*: [Projeto 6](projetos/lesson6_wine-classes.html)